name: TgBotLLM

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip>=21.0.1
  - setuptools>=51.0.0
  - aiosqlite
  - pip:
      - PyMuPDF
      - Spire
      - Spire.pdf
      - Spire.doc
      - Spire.Presentation
      - aiogram >= 3.5.0
      - python-dotenv
      - spire.xls
      - g4f[all]

